### ISSUE TITLE
l10ns 2.3.0 doesn't compile anymore

### ISSUE THREAD

**Issue by cvlmtg** [tinganho/l10ns#122] opened 2016-03-29 08:18 UTC
I've tried with both node 5.9.1 and node 4.4.1 and the error message is the same. I've set up different languages in my project even if at the moment only one has some values. I had this error with the DE language, and then I erased de-DE.json I got the same error on another language. I even tried erasing all the languages but the default one, and I still get the same error.

```
 (develop) ~/d/html5-app npm ls -g | grep l10ns
├─┬ l10ns@2.3.0
 (develop) ~/d/html5-app npm ls | grep l10ns
├─┬ l10ns@2.3.0
 (develop) ~/d/html5-app l10ns update
 (develop) ~/d/html5-app l10ns compile
Error: Cannot find module 'cldr-data/main/fr-FR/numbers'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new MessageFormat (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:36:5)
    at /Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/plugins/javascript/compiler.js:210:29
    at _fulfilled (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:749:13)
    at /Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:557:44
```

**Comment by tinganho** [comment] 2016-03-29 08:51
@cvlmtg sorry for the inconvience I made to you. I will try to make sure this problem gets fixed as soon as possible.

The problem is probably in the downstream CLDR repo. They seemed to have removed standard region for a language.

**Comment by cvlmtg** [comment] 2016-03-29 09:37
thanks!

**Comment by tinganho** [comment] 2016-03-29 10:16
@cvlmtg I pushed a new release `l10ns@2.3.1` could you please try it out.

**Comment by cvlmtg** [comment] 2016-03-29 13:16
sorry, I have another error

```
 (develop) ~/d/html5-app npm --depth=0 ls | grep l10ns
├── l10ns@2.3.1
 (develop) ~/d/html5-app npm --depth=0 ls -g | grep l10ns
├── l10ns@2.3.1
 (develop) ~/d/html5-app l10ns update
 (develop) ~/d/html5-app l10ns compile
Error: E_MISSING_BUNDLE: {"locale":"en-GB"}
    at createError (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:341:11)
    at validate (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:357:10)
    at Cldr.main (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/cldrjs/dist/cldr.js:663:3)
    at MessageFormat._readNumberFormatPatterns (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:1019:40)
    at MessageFormat._readNumberFormatsData (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:991:8)
    at new MessageFormat (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/libraries/MessageFormat/index.js:79:8)
    at /Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/plugins/javascript/compiler.js:210:29
    at _fulfilled (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/matteo/.nvf/installed/node-5.9.1/lib/node_modules/l10ns/node_modules/q/q.js:749:13)
```

**Comment by tinganho** [comment] 2016-03-29 13:48
@cvlmtg this is related to https://github.com/rxaviers/cldrjs/issues/41.

I'm not sure I can do much on my front. I advise you to use `l10ns@2.2.5` if you cannot wait. It uses an older version of CLDR.

Next major version will have a more proper testing infrastructure in place so these kind of bugs shouldn't appear so often.

**Comment by cvlmtg** [comment] 2016-03-29 15:26
I can use l10ns 2.2.5 meanwhile, thanks for the support!

**Comment by tinganho** [comment] 2016-07-02 03:04
I think this should be fixed by now.

**Closed by tinganho** 2016-07-02 03:04 UTC
